Add rod download functionality
FAIRmat-NFDI/pynxtools-raman pull request #18
Opened 2024-12-10 13:49 UTC by RonHildebrandt

The Raman Open Database is currently down. Here just a intial draft PR to extend the functionalities
- [ ] Test if the download works
- [ ] Add function to fetch a list of all possible .rod IDs

2025-02-03 09:43 UTC, lukaspie requested changes
Mostly good, some small suggestions here and there

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +# Downloading multiple .rod files
If you find the find, can you eventually bring these READMEs to a proper documentation? You can take the mkdocs setup from one of the other plugins. Can be a separate PR of course?

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +## Manually downloading
State here that you need to have `pynxtools-raman` installed for this to work.

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +Be careful: Do not trigger unneccsary amounts of downloads.
```suggestion
Be careful: Do not trigger unnecessary amounts of downloads.
```
Is this really such a problem? It is a downloadable DB after all.

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +## Add the command as script
```suggestion
## Make the bash script executable
```

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +## Exectutute the script
```suggestion
## Execute the script
```

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +`dataconverter <PATH_TO>/1000679.rod src/pynxtools_raman/config/config_file_rod.json --reader raman --nxdl NXraman --output rod_example_neuxs.nxs`
```suggestion
`dataconverter <PATH_TO>/1000679.rod src/pynxtools_raman/config/config_file_rod.json --reader raman --nxdl NXraman --output rod_example_nexus.nxs`
```

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +via the pynxtools-raman command:
Using the [`pynxtools` dataconverter](https://fairmat-nfdi.github.io/pynxtools/learn/dataconverter-and-readers.html) with the `pynxtools-raman` reader plugin:

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +# Automatec conversion of all .rod files to .nxs files
```suggestion
# Automatic conversion of all .rod files to .nxs files
```

2025-02-03 09:43 UTC, lukaspie commented on src/download_rod_files/README.md
> +## Add the command as script
```suggestion
## Make the bash script executable
```

2025-02-03 09:43 UTC, lukaspie commented on .gitignore
> +!src/download_rod_files/*.txt
You have this here, yet there are .txt files in the folder that are commited to git? Is this intentional?

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_get_file.py
> +    print(f"Initialized download of .rod file with ID '{rod_id}' from '{url}'.")
Make this a logger.info

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"Successfully received .rod file with ID '{rod_id}'")
logger.info

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"ConnectionError occured: {con_err}")
logger.error or logger.warning mabe?

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"CHTTPError occured: {http_err}")
logger.error or logger.warning mabe?

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"RequestException occured: {req_exc}")
logger.error or logger.warning mabe?

2025-02-03 09:43 UTC, lukaspie commented on src/pynxtools_raman/rod/rod_reader.py
> +                if value[0] == "'":
```suggestion
                if value.startswith("'"):
```

2025-02-17 08:51 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +# Downloading multiple .rod files
Yea, okay. Later then, created an issue for now: https://github.com/FAIRmat-NFDI/pynxtools-raman/issues/25

2025-02-17 08:55 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +## Manually downloading
done

2025-02-17 08:57 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +Be careful: Do not trigger unneccsary amounts of downloads.
Just wanted to emphasize some good practice. Removed the "Be careful".

2025-02-17 08:59 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +## Exectutute the script
done

2025-02-17 09:02 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +via the pynxtools-raman command:
done

2025-02-17 09:03 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +`dataconverter <PATH_TO>/1000679.rod src/pynxtools_raman/config/config_file_rod.json --reader raman --nxdl NXraman --output rod_example_neuxs.nxs`
done

2025-02-17 09:03 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +# Automatec conversion of all .rod files to .nxs files
done

2025-02-17 09:03 UTC, RonHildebrandt commented on src/download_rod_files/README.md
> +## Add the command as script
done

2025-02-17 09:26 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_get_file.py
> +    print(f"Initialized download of .rod file with ID '{rod_id}' from '{url}'.")
done

2025-02-17 09:26 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"Successfully received .rod file with ID '{rod_id}'")
done

2025-02-17 09:26 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"ConnectionError occured: {con_err}")
done (via logger.error)

2025-02-17 09:27 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_get_file.py
> +        print(f"CHTTPError occured: {http_err}")
done

2025-02-17 09:29 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_reader.py
> +                if value[0] == "'":
okay, just checked out why .startswith is better. Thanks for advice.

2025-02-17 09:31 UTC, RonHildebrandt commented on src/pynxtools_raman/rod/rod_reader.py
> +    if wavelength_nm is not None and resoltion_invers_cm is not None:
done

2025-02-17 11:19 UTC, lukaspie reviewed
LGTM

2025-02-17 11:19 UTC, lukaspie approved these changes
LGTM

2025-02-17 11:35 UTC, merged